### ISSUE TITLE
subject_id, trial_id unique?

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekds#1]
does the combination of subject_id and trial_id uniquely identify a single trial? if so, how do we notate when a single subject sees exactly the same stimulus twice?

**Comment by mikabr** [comment]
a combination of administration_id and trials_id identifies a single trial. is that a problem? a single subject seeing the same stimulus twice will be in two different trials, right?

**Comment by mcfrank** [comment]
yes, this is fixed by the inclusion of the stimuli table.
