### ISSUE TITLE
Are validators working?

### ISSUE THREAD

**Issue by smeylan** [langcog/peekds#10]
@lingerxu @mikabr The CSV format issues described in #8 and #9 suggest that the validation procedure in Peekds might not be properly linked against the schema. On the other hand, there could just be a mismatch such that the contents of Peekbank-hack do not represent the latest version of peekds

**Comment by lingerxu** [comment]
Yes, it is working when I checked in yesterday.

Validator checks csv files or tables against the json schema file on in peekbank: https://raw.githubusercontent.com/langcog/peekbank/master/static/peekbank-schema.json
