### ISSUE TITLE
make xy_data have the origin of the coordinates as bottom left

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekds#16]
we should put this in the specification and ensure that it is followed. Tobii for instances has the upper left as the origin.

**Comment by mzettersten** [comment]
currently noted in the peekbank column info / codebook spreadsheet: https://docs.google.com/spreadsheets/d/1Z24n9vfrAmEk6_HpoTSh58LnkmSGmNJagguRpI1jwdo/edit?usp=sharing

**Comment by mzettersten** [comment]
Should be resolved through documentation above.
