### ISSUE TITLE
some ages are in months and some are in years

### ISSUE THREAD

**Issue by mikabr** [langcog/peekds#23]

**Comment by mzettersten** [comment]
I think the decision was to track age in days. We could use the same conversion multipliers as have been used in e.g. metalab: (1 month = 30.44 days; 1 year = 365.25 days)

**Comment by mcfrank** [comment]
counterpoint, days are a bit of a pain to track, right? what about rounding
to the nearest standardized integer month? that also deals with
privacy/reidentifiabiity concerns...

**Comment by mzettersten** [comment]
works for me! I think since we are adding lab_age and lab_age and lab_age_units now as well, one could always go back to a more specific age (which seems like it would be the main reason to keep age in days). So having age as tracking nearest integer month seems fine to me for our purposes.

**Comment by mcfrank** [comment]
This seems like a lot of bookkeeping to me but I'm ok with it if others
are...
