### ISSUE TITLE
put_processed_data will not overwrite

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekds#25]
you have to erase the previous one, this is due to an apparent bug in `osfr::osf_upload`, registered here: https://github.com/ropensci/osfr/issues/130

there are also some issues with recursing directories that I haven't tested but we shouldn't need this functionality here.

**Comment by mcfrank** [comment]
seems like this is partially resolved?

**Comment by adriansteffan** [comment]
we are redoing the osf upload anyway, since osfr is broken, closing this one
