### ISSUE TITLE
Tzeltal does not appear to have a code in ISO 639-2/B

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekds#26]
Unless I'm missing it, it doesn't look to me like Tzeltal has a language code in ISO 639-2/B (sorry if I'm missing it). It  does seem to have one in ISO-639-3 (tzh - https://en.wikipedia.org/wiki/Tzeltal_language). So there's a question about whether we need to update the ISO codes.

It might be worth it to also have an "other" option in the full_phrase_language column, in case there are other issues like this  (right now just multiple and artificial  are alternate options.

@smeylan @mikabr

**Comment by mzettersten** [comment]
Marisa also noted that there could be other languages incoming that might have a similar issue, so it  might be good to build in some additional flexibility here.

**Comment by adriansteffan** [comment]
We fixed this by specifying the language in aux data in our new format
