### ISSUE TITLE
resampling and centering workflow

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekds#31]
resampling should happen *before* centering. to do this, we need to:
- [x] revise peekds to make sure that `resample_aoi` functions take `t` rather than `t_norm`
- [ ] document workflow in our import guide (that isn't started) 😛 
- [ ] consider adding error checking / documentation to resample functions

**Comment by lingerxu** [comment]
added a safe check before re-sample to make sure the table has correct columns
