### ISSUE TITLE
Checks to add to the validator

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekds#40]
- [x] ensure that there are no duplicate trial types that only differ by id
- [x] add additional CDI checks: validate specific values in the CDI format
- [x] sanity check age by doing centralized lab_age and lab_age_units conversion
- [x] ensure that there are no duplicate stimulus rows that only differ by id
- [x] store a render of 1 or 2 timecourse plots at the end
- [x] make sure primary keys are sequential (0,1,2,3.... - no missing ids)
- [x] no duplicate trial_order values within administration
- [x] validate language (full phrase and native language) against ISO language code
- [x] check if exclusion reason is empty for all originally included trials
- [x] check if there are surperfluous columns (has been linked to invalid id assignments before and makes validation generally annoying, as joins break) 

Maybe:
- [x] check to see if there are orphan ids anywhere (after joining)
- [x] a quick report of a few basic dataset facts: # of subjects, # of administrations, average trials per participant, min/ max values, maybe balance of left/ right target image/ distractor image to check some counterbalancing, average trial durations (min/ max values); add MCDI min-max value check, exclusion info

**Comment by adriansteffan** [comment]
Finished up all points here! The report code still lives in the common code snippets in the import repository for convenience, we can move that part over here once it is finalized
