### ISSUE TITLE
output CSV should be called "datasets.csv" not "dataset.csv"

### ISSUE THREAD

**Issue by smeylan** [langcog/peekds#8]

**Comment by lingerxu** [comment]
Yes, it should be called datasets.csv. If named otherwise, won't pass validator function -- validate_for_db_import(dataset_type, dir_csv)

**Comment by mzettersten** [comment]
@rosemschneider see also my comment on #9. If this is in reference to yurovsky_2017, I don't think that is ready for "primetime" yet (and it hasn't passed a validator to my knowledge). To my knowledge, it's just reflook_v1 in smi_raw and the icoder data that should ready to go. I think reflook_v3 should be ready soon-ish.
