### ISSUE TITLE
dataset.id -> dataset_id; should be int

### ISSUE THREAD

**Issue by smeylan** [langcog/peekds#9]
encountered in Yurovsky 2017:  `defaultdict(None, {'id': 'yurovsky_2017', 'Unnamed: 0': 1, 'sample_rate': '30hz', 'monitor_size': '1280x720', 'method': 'preferential looking', 'tracker': 'SMI Red'})`

**Comment by smeylan** [comment]
human-raedable string id should be called lab_dataset_id

**Comment by mzettersten** [comment]
I don't think this dataset (yurovsky 2017) has been looked at since relatively early in the week, so I assume there are a number of things to update. @rosemschneider  I can look into this as well.

**Comment by mcfrank** [comment]
I asked @dyurovsky and he was going to look around for the point of
disambiguation and stimulus info.
